### ISSUE TITLE
ActionPack::VERSION::MAJOR >= 5 behavior different from < 5

### ISSUE THREAD

**Issue by consti** [kenchan/rspec-default_http_header#2]
In the current version of the gem no default_headers will be set if no `headers` argument is passed to the http method.

Example:

``` ruby
# Will not add any default headers
get '/'

# Will add default headers
get '/', headers: { this_will_be_merged: true }
```

This is a fix that will add the default_headers regardless if any other headers were set:

``` ruby
if ActionPack::VERSION::MAJOR >= 5
  define_method(m) do |path, *args|
    args[0] ||= {}
    args[0][:headers] ||= {}
    args[0][:headers].merge!(default_headers)

    super(path, *args)
  end
else
```

**Comment by kenchan** [comment]
Thanks for your report.

It is fixed in the [v0.0.3](https://rubygems.org/gems/rspec-default_http_header/versions/0.0.3). Try out the new version, please.
